"""add language to posts

Revision ID: 506fe06360c0
Revises: 7cb4ea7ecbfd
Create Date: 2025-02-06 16:03:18.911290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506fe06360c0'
down_revision = '7cb4ea7ecbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
